import type { ComplianceOutlook } from "../interfaces/metricsDashboard";

export const MockPolicies: ComplianceOutlook[] = [
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-13T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-14T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-003",
    "name": "Ensure Tagging Compliance",
    "engine": "TFPolicy",
    "type": "Best Practices",
    "severity": "Advisory",
    "region": "APAC",
    "provider": "GCP",
    "status": "Passed",
    "last_run": "2026-05-12T14:15:00Z",
    "frameworks": "Internal"
  },
  {
    "id": "pol-004",
    "name": "Database Encryption at Rest",
    "engine": "Sentinel",
    "type": "Storage",
    "severity": "Hard-M",
    "region": "LATAM",
    "provider": "Alibaba",
    "status": "Failed",
    "last_run": "2026-05-14T11:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-005",
    "name": "IAM Root Access MFA",
    "engine": "OPA",
    "type": "Identity",
    "severity": "Hard-M",
    "region": "MENA",
    "provider": "AWS",
    "status": "Passed",
    "last_run": "2026-05-14T09:00:00Z",
    "frameworks": "CIS Benchmark"
  },
  {
    "id": "pol-006",
    "name": "VPC Flow Logs Enabled",
    "engine": "TFPolicy",
    "type": "Networking",
    "severity": "Advisory",
    "region": "USA",
    "provider": "Oracle Cloud",
    "status": "Failed",
    "last_run": "2026-05-13T22:30:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-007",
    "name": "Unused Elastic IPs",
    "engine": "Sentinel",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "AWS",
    "status": "Passed",
    "last_run": "2026-05-14T12:00:00Z",
    "frameworks": "Internal"
  },
  {
    "id": "pol-008",
    "name": "Object Storage Versioning",
    "engine": "OPA",
    "type": "Storage",
    "severity": "Soft-M",
    "region": "APAC",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-11T16:45:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-009",
    "name": "Kubernetes Ingress Security",
    "engine": "OPA",
    "type": "Networking",
    "severity": "Hard-M",
    "region": "LATAM",
    "provider": "Red Hat",
    "status": "Failed",
    "last_run": "2026-05-14T07:15:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-010",
    "name": "Orphaned Snapshots",
    "engine": "Sentinel",
    "type": "Cost",
    "severity": "Advisory",
    "region": "USA",
    "provider": "GCP",
    "status": "Passed",
    "last_run": "2026-05-13T19:20:00Z",
    "frameworks": "Internal"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-14T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-011",
    "name": "Restrict SSH Access (0.0.0.0/0)",
    "engine": "TFPolicy",
    "type": "Security",
    "severity": "Hard-M",
    "region": "MENA",
    "provider": "Others",
    "status": "Failed",
    "last_run": "2026-05-14T13:40:00Z",
    "frameworks": "CIS Benchmark"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-12T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-012",
    "name": "Instance Termination Protection",
    "engine": "Sentinel",
    "type": "Compute",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-14T10:10:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-013",
    "name": "Password Policy Min Length",
    "engine": "OPA",
    "type": "Identity",
    "severity": "Hard-M",
    "region": "APAC",
    "provider": "Oracle Cloud",
    "status": "Passed",
    "last_run": "2026-05-12T08:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-11T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-014",
    "name": "Load Balancer TLS 1.2+",
    "engine": "TFPolicy",
    "type": "Networking",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-14T15:20:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-015",
    "name": "Stale Admin Accounts",
    "engine": "Sentinel",
    "type": "Best Practices",
    "severity": "Soft-M",
    "region": "LATAM",
    "provider": "GCP",
    "status": "Passed",
    "last_run": "2026-05-13T11:55:00Z",
    "frameworks": "Internal"
  },
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-12T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-11T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-10T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-10T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-09T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-09T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-08T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-08T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-07T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-07T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-06T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-06T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-05T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-05T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-04T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-04T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-03T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-03T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-02T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-02T08:30:00Z",
    "frameworks": "SOC2"
  },
  {
    "id": "pol-001",
    "name": "Restrict S3 Public Access",
    "engine": "Sentinel",
    "type": "Security",
    "severity": "Hard-M",
    "region": "USA",
    "provider": "AWS",
    "status": "Failed",
    "last_run": "2026-05-01T10:00:00Z",
    "frameworks": "ISO/IEC 27001:2013"
  },
  {
    "id": "pol-002",
    "name": "Max Compute Instance Size",
    "engine": "OPA",
    "type": "Cost",
    "severity": "Soft-M",
    "region": "EU",
    "provider": "Azure",
    "status": "Passed",
    "last_run": "2026-05-01T08:30:00Z",
    "frameworks": "SOC2"
  }
]