import type { UngovernedResources } from '../interfaces/ungovernedResources';

export const mockUngovernedResources: UngovernedResources[] = [
  // ================= PAYLOAD FOR MAY (3 Entries) =================
  {
    id: "ws-res-001",
    name: "production-ent-platform-vpc-sg",
    type: "",
    policy_engine: "",
    severity: "",
    region: "USA",
    provider: "Azure",
    environment: "Production",
    status: "Unchecked",
    last_run: "2026-05-21T09:12:00Z",
    run_id: "v9768",
    resources_attached: 15,
    triggered_by: "xyz@ibm.com",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-002",
    name: "production-ent-platform-s3-bucket",
    type: "",
    policy_engine: "",
    severity: "",
    region: "USA",
    provider: "AWS",
    status: "Unchecked",
    resources_attached: 8,
    last_run: "2026-05-21T09:12:00Z",
    environment: "Production",
    run_id: "v9768",
    triggered_by: "xyz@ibm.com",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-003",
    name: "test-aws-ec2-instance",
    type: "",
    policy_engine: "",
    severity: "",
    region: "EU",
    provider: "AWS",
    status: "Unchecked",
    environment: "Testing",
    resources_attached: 3,
    last_run: "2026-05-14T14:22:15Z",
    run_id: "v9654",
    triggered_by: "abc@ibm.com",
    source: "VCS",
    policies_attached: []
  },

  // ================= PAYLOAD FOR APRIL (4 Entries) =================
  {
    id: "ws-res-004",
    name: "backend-apis-db-subnet",
    type: "",
    policy_engine: "",
    severity: "",
    region: "APAC",
    provider: "GCP",
    status: "Unchecked",
    environment: "Production",
    last_run: "2026-04-28T11:05:30Z",
    resources_attached: 5,
    run_id: "v9512",
    triggered_by: "api-service-account",
    source: "API",
    policies_attached: []
  },
  {
    id: "ws-res-005",
    name: "frontend-platform-cdn",
    type: "",
    policy_engine: "",
    severity: "",
    region: "MENA",
    provider: "Alibaba",
    status: "Unchecked",
    last_run: "2026-04-19T16:40:00Z",
    run_id: "v9421",
    resources_attached: 2,
    environment: "Development",
    triggered_by: "git-bot",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-006",
    name: "data-lake-storage-blob",
    type: "",
    policy_engine: "",
    severity: "",
    region: "LATAM",
    provider: "Oracle Cloud",
    status: "Unchecked",
    last_run: "2026-04-12T08:15:22Z",
    environment: "Production",
    run_id: "v9311",
    resources_attached: 10,
    triggered_by: "xyz@ibm.com",
    source: "CLI",
    policies_attached: []
  },
  {
    id: "ws-res-007",
    name: "auth-service-k8s-cluster",
    type: "",
    policy_engine: "",
    severity: "",
    region: "USA",
    provider: "Red Hat",
    status: "Unchecked",
    last_run: "2026-04-03T22:31:05Z",
    environment: "Production",
    run_id: "v9204",
    resources_attached: 12,
    triggered_by: "platform-team@ibm.com",
    source: "VCS",
    policies_attached: []
  },

  // ================= PAYLOAD FOR MARCH (5 Entries) =================
  {
    id: "ws-res-008",
    name: "billing-api-gateway",
    type: "",
    policy_engine: "",
    severity: "",
    region: "EU",
    provider: "AWS",
    environment: "Testing",
    status: "Unchecked",
    last_run: "2026-03-25T13:14:15Z",
    run_id: "v9188",
    triggered_by: "abc@ibm.com",
    resources_attached: 4,
    source: "API",
    policies_attached: []
  },
  {
    id: "ws-res-009",
    name: "cache-redis-cluster",
    type: "",
    policy_engine: "",
    severity: "",
    region: "USA",
    provider: "Azure",
    environment: "Production",
    status: "Unchecked",
    last_run: "2026-03-20T10:45:00Z",
    resources_attached: 6,
    run_id: "v9075",
    triggered_by: "xyz@ibm.com",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-010",
    name: "search-es-nodes",
    type: "",
    policy_engine: "",
    severity: "",
    region: "APAC",
    provider: "GCP",
    status: "Unchecked",
    environment: "Testing",
    last_run: "2026-03-15T17:20:11Z",
    resources_attached: 7,
    run_id: "v8964",
    triggered_by: "infra-bot@ibm.com",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-011",
    name: "logging-fluentd-daemon",
    type: "",
    policy_engine: "",
    severity: "",
    region: "MENA",
    provider: "AWS",
    status: "Unchecked",
    environment: "Development",
    last_run: "2026-03-09T04:12:55Z",
    resources_attached: 1,
    run_id: "v8852",
    triggered_by: "git-bot",
    source: "CLI",
    policies_attached: []
  },
  {
    id: "ws-res-012",
    name: "reporting-db-replica",
    type: "",
    policy_engine: "",
    severity: "",
    region: "LATAM",
    provider: "Oracle Cloud",
    environment: "Production",
    status: "Unchecked",
    last_run: "2026-03-02T11:55:40Z",
    resources_attached: 9,
    run_id: "v8741",
    triggered_by: "xyz@ibm.com",
    source: "VCS",
    policies_attached: []
  },

  // ================= PAYLOAD FOR FEBRUARY (8 Entries) =================
  {
    id: "ws-res-013",
    name: "notification-sms-hub",
    type: "",
    policy_engine: "",
    severity: "",
    region: "USA",
    provider: "AWS",
    status: "Unchecked",
    environment: "Testing",
    last_run: "2026-02-27T09:00:00Z",
    run_id: "v8620",
    resources_attached: 3,
    triggered_by: "abc@ibm.com",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-014",
    name: "analytics-spark-master",
    type: "",
    policy_engine: "",
    severity: "",
    region: "EU",
    provider: "GCP",
    status: "Unchecked",
    environment: "Production",
    last_run: "2026-02-24T15:30:45Z",
    resources_attached: 5,
    run_id: "v8519",
    triggered_by: "api-service-account",
    source: "API",
    policies_attached: []
  },
  {
    id: "ws-res-015",
    name: "recommendation-engine-model",
    type: "",
    policy_engine: "",
    severity: "",
    region: "APAC",
    provider: "Azure",
    status: "Unchecked",
    environment: "Testing",
    resources_attached: 2,
    last_run: "2026-02-20T18:12:10Z",
    run_id: "v8403",
    triggered_by: "ml-ops@ibm.com",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-016",
    name: "media-transcoder-vm",
    type: "",
    policy_engine: "",
    severity: "",
    region: "USA",
    provider: "Alibaba",
    status: "Unchecked",
    environment: "Development",
    resources_attached: 4,
    last_run: "2026-02-17T07:22:30Z",
    run_id: "v8391",
    triggered_by: "xyz@ibm.com",
    source: "CLI",
    policies_attached: []
  },
  {
    id: "ws-res-017",
    name: "payment-webhook-listener",
    type: "",
    policy_engine: "",
    severity: "",
    region: "EU",
    provider: "AWS",
    status: "Unchecked",
    environment: "Production",
    resources_attached: 11,
    last_run: "2026-02-13T12:05:14Z",
    run_id: "v8211",
    triggered_by: "git-bot",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-018",
    name: "user-profile-cache",
    type: "",
    policy_engine: "",
    severity: "",
    region: "LATAM",
    provider: "Azure",
    status: "Unchecked",
    resources_attached: 6,
    environment: "Testing",
    last_run: "2026-02-10T14:45:00Z",
    run_id: "v8105",
    triggered_by: "abc@ibm.com",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-019",
    name: "partner-integration-endpoint",
    type: "",
    policy_engine: "",
    severity: "",
    region: "MENA",
    provider: "Oracle Cloud",
    status: "Unchecked",
    environment: "Production",
    resources_attached: 8,
    last_run: "2026-02-06T10:11:25Z",
    run_id: "v8042",
    triggered_by: "xyz@ibm.com",
    source: "API",
    policies_attached: []
  },
  {
    id: "ws-res-020",
    name: "monitoring-grafana-dashboard",
    type: "",
    policy_engine: "",
    severity: "",
    region: "USA",
    provider: "Red Hat",
    resources_attached: 1,
    status: "Unchecked",
    environment: "Development",
    last_run: "2026-02-02T16:20:00Z",
    run_id: "v7960",
    triggered_by: "platform-team@ibm.com",
    source: "VCS",
    policies_attached: []
  },

  // ================= PAYLOAD FOR JANUARY (10 Entries) =================
  {
    id: "ws-res-021",
    name: "audit-logs-archiver",
    type: "",
    policy_engine: "",
    severity: "",
    region: "USA",
    provider: "AWS",
    status: "Unchecked",
    resources_attached: 4,
    environment: "Production",
    last_run: "2026-01-29T08:50:11Z",
    run_id: "v7851",
    triggered_by: "xyz@ibm.com",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-022",
    name: "security-bastion-host",
    type: "",
    policy_engine: "",
    severity: "",
    region: "EU",
    resources_attached: 2,
    provider: "AWS",
    status: "Unchecked",
    environment: "Production",
    last_run: "2026-01-26T21:14:40Z",
    run_id: "v7740",
    triggered_by: "sec-ops@ibm.com",
    source: "CLI",
    policies_attached: []
  },
  {
    id: "ws-res-023",
    name: "inventory-db-cluster",
    type: "",
    policy_engine: "",
    severity: "",
    region: "APAC",
    provider: "GCP",
    status: "Unchecked",
    resources_attached: 9,
    environment: "Production",
    last_run: "2026-01-23T11:30:00Z",
    run_id: "v7639",
    triggered_by: "abc@ibm.com",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-024",
    name: "marketing-landing-page-bucket",
    type: "",
    policy_engine: "",
    severity: "",
    region: "USA",
    provider: "Azure",
    resources_attached: 3,
    status: "Unchecked",
    environment: "Testing",
    last_run: "2026-01-20T15:05:12Z",
    run_id: "v7522",
    triggered_by: "git-bot",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-025",
    name: "geo-location-lookup-service",
    type: "",
    policy_engine: "",
    severity: "",
    region: "LATAM",
    provider: "Google Cloud",
    status: "Unchecked",
    environment: "Production",
    resources_attached: 7,
    last_run: "2026-01-17T09:44:35Z",
    run_id: "v7411",
    triggered_by: "api-service-account",
    source: "API",
    policies_attached: []
  },
  {
    id: "ws-res-026",
    name: "image-processor-queue",
    type: "",
    policy_engine: "",
    severity: "",
    region: "MENA",
    provider: "Alibaba",
    resources_attached: 5,
    status: "Unchecked",
    environment: "Production",
    last_run: "2026-01-14T13:22:00Z",
    run_id: "v7302",
    triggered_by: "xyz@ibm.com",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-027",
    name: "session-state-store",
    type: "",
    policy_engine: "",
    severity: "",
    region: "USA",
    provider: "AWS",    
    resources_attached: 2,
    environment: "Testing",
    status: "Unchecked",
    last_run: "2026-01-11T17:10:55Z",
    run_id: "v7219",
    triggered_by: "abc@ibm.com",
    source: "CLI",
    policies_attached: []
  },
  {
    id: "ws-res-028",
    name: "feedback-collection-form",
    type: "",
    policy_engine: "",
    severity: "",
    region: "EU",
    provider: "Azure",
    resources_attached: 1,
    status: "Unchecked",
    environment: "Development",
    last_run: "2026-01-08T10:00:22Z",
    run_id: "v7104",
    triggered_by: "git-bot",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-029",
    name: "dns-routing-policies",
    type: "",
    policy_engine: "",
    severity: "",
    region: "APAC",
    provider: "Oracle Cloud",
    resources_attached: 4,
    status: "Unchecked",
    environment: "Production",
    last_run: "2026-01-05T14:55:00Z",
    run_id: "v7022",
    triggered_by: "platform-team@ibm.com",
    source: "VCS",
    policies_attached: []
  },
  {
    id: "ws-res-030",
    name: "compliance-archive-vault",
    type: "",
    policy_engine: "",
    severity: "",
    region: "USA",
    provider: "AWS",
    resources_attached: 3,
    status: "Unchecked",
    environment: "Production",
    last_run: "2026-01-02T09:15:30Z",
    run_id: "v6911",
    triggered_by: "xyz@ibm.com",
    source: "VCS",
    policies_attached: []
  }
];